namespace AssemblyInterpreter.Entities
{
    public enum Commands
    { 
        read = 128,
        copy = 64,
        add = 0,
        readAdd = 128,
        copyAdd = 64,
        sub = 1,
        readSub = 129,
        copySub = 65,
        and=2,
        readAnd=130,
        copyAnd=66,
        or=3,
        readOr=131,
        copyOr=67,
        not=4,
        readNot=132,
        copyNot=68,
        xor=5,
        readXor=133,
        copyXor=69,
        shiftRight=6,
        readShiftRight=134,
        copyShiftRight=70,
        shiftLeft=7,
        readShiftLeft=135,
        copyShiftLeft=71,
        multiply=8,
        readMultiply=136,
        copyMultiply=72,
        // from RAM
        call=12,
        ret=13, 
        go=14,
        // from Stack
        stack=16,
        eq=32,
        readEq=160,
        copyEq=96,
        neq=33,
        readNeq=161,
        copyNeq=97,
        lt=34,
        readLt=162,
        copyLt=98,
        lte=35,
        readLte=163,
        copyLte=99,
        gt=36,
        readGt=164,
        copyGt=100,
        gte=37,
        readGte=165,
        copyGte=101
    }
}
